/*
 * msg_proc.c: implementation of the remote procedure "printmessage"
 */

#include <stdio.h>
#include <rpc/rpc.h> /* always needed */
#include "msg.h" /* need this too: msg.h will be generated by rpcgen */

/*
 * Remote verson of "printmessage"
 */
int* printmessage_1_svc(char** msg, struct svc_req * svc) {
  static int result; /* must be static! */
  FILE *f;
  f = fopen("/dev/console", "w");
  if (f == NULL) {
    result = 0;
    return (&result);
  }
  fprintf(f, "%s_svc\n", *msg);
  fclose(f);
  result = 1;
  return (&result);
}
